### ISSUE TITLE
Mixin version missing with latest release

### ISSUE THREAD

**Issue by vdice** [MChorfa/porter-helm3#31]
This mixin's version appears to be missing or ill-formatted.

```
$ porter version
porter v0.38.6 (43d077da)

$ porter mixin install helm3 --version v0.1.3 --url https://github.com/MChorfa/porter-helm3/releases/download
installed helm3 mixin  ()
```

Example with version:

```
$ porter mixin install kubernetes --feed-url https://cdn.porter.sh/mixins/atom.xml
installed kubernetes mixin v0.28.4 (f7dd720)
```

**Comment by vdice** [comment]
Update: not sure if this is a Porter/cli issue.  We see the correct version when using the atom feed url:

```
$ porter mixin install helm3 --feed-url https://mchorfa.github.io/porter-helm3/atom.xml
installed helm3 mixin v0.1.13 (c38b6cd)
```

**Comment by carolynvs** [comment]
I believe the problem is that someone got confused about --feed-url vs --url, which then prompted a change to the atom.xml file hosted in this repository. That change introduced duplicate entries, and also a "latest" url that was invalid.

The fix is to revert the last change to your docs/atom.xml file. I'll submit a PR for that.

In the meantime, you can test out that the old version works by running

```
porter mixin install helm3 --feed-url https://raw.githubusercontent.com/MChorfa/porter-helm3/e643fad90573f208b68577d917708462986f5eb8/build/atom-template.xml
```
